server:
  port: 5050

spring:
  application:
    name: pph-gateway
  cloud:
    # Register pph-gateway module to nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # Configure gateway
    gateway:
      routes: # Configure routes, can have multiple route configurations
        # Route: to pph-commodity product management module
        # Note: Because /api/commodity/** is a more precise path, it must be placed before the /api/** route group
        # Otherwise it will report {"msg":"invalid token","code":401}
        - id: pph_commodity_route
          uri: lb://pph-commodity
          predicates:
            - Path=/api/commodity/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # Route: to pph-service module, get upload image aliyun OSS policy and signature
        - id: pph_service_route
          uri: lb://pph-service
          predicates:
            - Path=/api/service/**
          filters:
            - RewritePath=/api/service/(?<segment>.*),/$\{segment}
        # Route: to renren-fast login module
        - id: pph_renren_fast_route
          # Configure load balancing
          uri: lb://renren-fast
          # Assertion, if path contains /api, route to renren-fast
          predicates:
            - Path=/api/**
          # Path rewrite, means api is obtained, then find the real request address
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        # Route: configure nginx
        - id: pph_host_route
          uri: lb://pph-commodity
          predicates:
            - Host=**.productpilothome.com
