spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.33.10:3306/pph_commodity?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    # Configure alibaba OSS related parameters - sensitive information moved to Nacos configuration center
    alicloud:
      oss:
        endpoint: ${ALIYUN_OSS_ENDPOINT:oss-us-west-1.aliyuncs.com}
      access-key: ${ALIYUN_ACCESS_KEY:your-access-key}
      secret-key: ${ALIYUN_SECRET_KEY:your-secret-key}
    # Register pph-commodity microservice module to nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #1. Disable thymeleaf cache, so when frontend pages change, you can see the effect
  #2. In production environment, set cache to true, enable cache, improve efficiency
  thymeleaf:
    cache: false
  application:
    name: pph-commodity

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # Configure primary key auto increment
      logic-delete-value: 0 # Logic deleted value (default is 1, adjusted to our own)
      logic-not-delete-value: 1 # Logic not deleted value (default is 0, adjusted to our own)
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # Configure MyBatis-Plus output SQL statements