#server:
#  port: 7070
#
#spring:
#  cloud:
##   add aliyun oss configuration
#    alicloud:
#      access-key: YOUR_ALIYUN_ACCESS_KEY
#      secret-key: YOUR_ALIYUN_SECRET_KEY
#      oss:
#        endpoint: YOUR_ALIYUN_OSS_ENDPOINT
#        bucket: product-pilot-home
#    # Register pph-service module to nacos
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: pph-service